import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  type CountsSnapshot,
  canonicalJson,
  type MinimizationConfig,
  methodSha256,
  minimize,
  uniformDraw,
} from "@rtsm-core/core";
import { describe, expect, it } from "vitest";

/** Golden vectors generated by the R reference implementation
 * (tools/minimization-reference.R) — the statistician reviews the R, the
 * runtime runs the TypeScript, this test is the bridge (ADR-0008). */
interface GoldenVector {
  label: string;
  arms: string[];
  factors: { name: string; levels: string[]; weight: number }[];
  p: number;
  counts: CountsSnapshot;
  covariates: Record<string, string>;
  expected: {
    imbalanceScores: Record<string, number>;
    armProbabilities: Record<string, number>;
  };
}

const vectors: GoldenVector[] = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL("../../../packages/core/test-vectors/minimization-vectors.json", import.meta.url),
    ),
    "utf8",
  ),
);

function config(v: GoldenVector): MinimizationConfig {
  return {
    method: "pocock-simon",
    imbalanceMetric: "range",
    arms: v.arms,
    factors: v.factors,
    p: v.p,
  };
}

describe("minimization engine vs the R oracle", () => {
  it("loads a non-trivial vector battery", () => {
    expect(vectors.length).toBeGreaterThanOrEqual(40);
  });

  for (const v of vectors) {
    it(`agrees on: ${v.label}`, () => {
      const result = minimize(config(v), v.counts, v.covariates, 0.5);
      for (const arm of v.arms) {
        expect(result.imbalanceScores[arm]).toBe(v.expected.imbalanceScores[arm]);
        expect(result.armProbabilities[arm]).toBeCloseTo(
          v.expected.armProbabilities[arm] as number,
          14,
        );
      }
    });
  }
});

describe("minimization engine", () => {
  const cfg: MinimizationConfig = {
    method: "pocock-simon",
    imbalanceMetric: "range",
    arms: ["Arm X", "Arm Y"],
    factors: [{ name: "stage", levels: ["I", "II"], weight: 1 }],
    p: 0.8,
  };
  const counts: CountsSnapshot = {
    // Arm X ahead at stage I: assigning to Arm Y minimizes the range.
    stage: { I: { "Arm X": 3, "Arm Y": 1 }, II: { "Arm X": 0, "Arm Y": 0 } },
  };

  it("favors the minimizing arm with probability p and selects by cumulative bucket", () => {
    const result = minimize(cfg, counts, { stage: "I" }, 0.5);
    expect(result.armProbabilities).toEqual({ "Arm X": 1 - 0.8, "Arm Y": 0.8 });
    // Arms accumulate in config order: [0, 0.2) -> Arm X, [0.2, 1) -> Arm Y.
    expect(minimize(cfg, counts, { stage: "I" }, 0.19).chosenArm).toBe("Arm X");
    expect(minimize(cfg, counts, { stage: "I" }, 0.21).chosenArm).toBe("Arm Y");
    expect(minimize(cfg, counts, { stage: "I" }, 0.999999).chosenArm).toBe("Arm Y");
  });

  it("gives the first subject a pure equal-probability draw", () => {
    const zero: CountsSnapshot = {
      stage: { I: { "Arm X": 0, "Arm Y": 0 }, II: { "Arm X": 0, "Arm Y": 0 } },
    };
    const result = minimize(cfg, zero, { stage: "II" }, 0.49);
    expect(result.armProbabilities).toEqual({ "Arm X": 0.5, "Arm Y": 0.5 });
    expect(result.chosenArm).toBe("Arm X");
    expect(minimize(cfg, zero, { stage: "II" }, 0.51).chosenArm).toBe("Arm Y");
  });

  it("rejects a missing or unconfigured covariate with an arm-free error", () => {
    expect(() => minimize(cfg, counts, {}, 0.5)).toThrowError(/factor "stage"/);
    expect(() => minimize(cfg, counts, { stage: "IV" }, 0.5)).toThrowError(/not a configured/);
    for (const fn of [
      () => minimize(cfg, counts, {}, 0.5),
      () => minimize(cfg, counts, { stage: "IV" }, 0.5),
    ]) {
      try {
        fn();
      } catch (err) {
        expect((err as Error).message).not.toContain("Arm");
      }
    }
  });
});

describe("counter-based RNG", () => {
  it("is deterministic in (seed, index) and stays in [0, 1)", () => {
    const seed = "0123456789abcdef0123456789abcdef";
    expect(uniformDraw(seed, 1)).toBe(uniformDraw(seed, 1));
    expect(uniformDraw(seed, 1)).not.toBe(uniformDraw(seed, 2));
    expect(uniformDraw(seed, 1)).not.toBe(uniformDraw(`${seed}x`, 1));
    for (let i = 1; i <= 1000; i++) {
      const u = uniformDraw(seed, i);
      expect(u).toBeGreaterThanOrEqual(0);
      expect(u).toBeLessThan(1);
    }
  });
});

describe("canonical config hash", () => {
  it("is key-order independent and seed-sensitive", () => {
    expect(canonicalJson({ b: 1, a: [{ d: 2, c: 3 }] })).toBe(
      canonicalJson({ a: [{ c: 3, d: 2 }], b: 1 }),
    );
    const cfg: MinimizationConfig = {
      method: "pocock-simon",
      imbalanceMetric: "range",
      arms: ["Arm X", "Arm Y"],
      factors: [{ name: "stage", levels: ["I", "II"], weight: 1 }],
      p: 0.8,
    };
    expect(methodSha256(cfg, "seed-1")).toMatch(/^[0-9a-f]{64}$/);
    expect(methodSha256(cfg, "seed-1")).not.toBe(methodSha256(cfg, "seed-2"));
    expect(methodSha256(cfg, "seed-1")).not.toBe(methodSha256({ ...cfg, p: 0.9 }, "seed-1"));
  });
});
